---
- hosts: baseinstall
  become: true
  tasks:
    - include: packages.yml
    - include: users.yml
    - include: config.yml
    - include: install_misc.yml
    - include: install_asterisk.yml
    - include: install_asterisk_helpers.yml version={{ conf_version }}
    - include: update_asterisk.yml version={{ conf_version }}
