---
- name: load generic secrets
  include_vars: "deploy/deploy_digitalocean_secrets.yml"
  no_log: true
# delete does not work with name, only id
- name: get data including droplet id
  digital_ocean:
    unique_name: yes
    api_token: "{{ deploy_access_token }}"
    name: futel-prod-back
  register: message  
- name: delete futel-prod-back
  digital_ocean:
    state: deleted
    command: droplet
    id: "{{ message.droplet.id }}"
    api_token: "{{ deploy_access_token }}"
