---
- name: load conf
  include_vars: "deploy/conf.yml"
- name: clean sounds directories
  file:
    path: "{{ asterisk_sound_directory }}"
    state: absent
- name: clean sounds directories
  file:
    path: "{{ asterisk_sound_directory }}"
    state: directory
- name: update and copy sounds
  command: ruby scripts/update_audio_assets.rb {{ asterisk_sound_directory }}/{{ item }} {{ asset_directory }}/{{ item }}
  with_items:
    - futel/church-of-robotron
    - futel/conversations
    - futel/longmont
    - futel/missed-connections
    - futel/oracle-dead-interstitial-long
    - futel/oracle-dead-interstitial-short
    - futel/oracle-dead-oracle
    - futel/peoples-homes
    - futel/sequence-challenge
    - futel/wildcard-line
    - futel/williams-long
    - futel/williams-short
    - en/statements/anzie-wumpus
    - en/statements/challenge
    - en/statements/conversations
    - en/statements/karl-oracle-dead
    - en/statements/karl_quuux
    - en/statements/karl-robotron
    - en/statements/karl-voicemail-ivr
    - en/statements/karl-wildcard-line
    - en/statements/konami
    - en/statements/missed-connections
    - en/statements/peoples-homes
    - en/statements/sailor
    - en/statements/tishbite
    - en/futelconf
    - es/statements/missed-connections
    - es/statements/sailor
