---
- name: load secrets
  include_vars: "deploy_digitalocean_secrets_digitalocean.yml"
  no_log: true
# XXX we are running in packer, this is just finding the droplet id  
- name: create droplet
  community.digitalocean.digital_ocean_droplet:
    state: present
    name: assetsbuild
    unique_name: yes
    oauth_token: "{{ deploy_access_token }}"
    image: "centos-8-x64"
    size: s-1vcpu-1gb
    region: sfo3
  register: droplet_message
- name: create block storage
  community.digitalocean.digital_ocean_block_storage:
    state: present
    command: create
    oauth_token: "{{ deploy_access_token }}"
    region: sfo3
    block_size: 10
    volume_name: assetsbuild
- name: attach block storage to droplet
  community.digitalocean.digital_ocean_block_storage:
    state: present
    command: attach
    oauth_token: "{{ deploy_access_token }}"
    volume_name: assetsbuild
    region: sfo3
    droplet_id: "{{ droplet_message.data.droplet.id }}"
